<?php

namespace AppBundle\Entity;

/**
 * BlogPostrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostrRepository extends \Doctrine\ORM\EntityRepository
{
}
